#PLAYBOOK
---
#PLAY
- name: deploy
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #RUN APT UPDATE
    - name: apt update
      #ACTION
      apt:  update_cache=yes
            force_apt_get=yes
            cache_valid_time=3600
    #RUN APT UPGRADE
    - name: apt upgrade
      #ACTION
      apt:  upgrade=dist
            force_apt_get=yes
    #RUN APT INSTALL SAMBA
    - name: install samba
      #ACTION
      apt:
        name: ['samba']
        state: latest
    #CREATE SHARED DIRECTORY
    - name: create shared directory
      #ACTION
      file:
        path: /home/vagrant/samba/
        state: directory
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"
    #ADD SHARED DIRECTORY TO THE SAMBA CONFIG
    - name: add shared directory config
      #ACTION
      blockinfile:
        path:  /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [samba]
            comment = Samba on Ubuntu
            path = /home/vagrant/samba
            read only = yes
            browsable = yes
      notify: Reload Samba
    #DEFINE SAMBA USER
    - name: set Samba passwords for each user
      #ACTION
      shell: "printf '123\n123\n' | smbpasswd -a vagrant"
  handlers:
    #RESTART SAMBA SERVICE
    - name: Reload Samba
      service:
        name: smbd
        state: restarted