#PLAYBOOK
---
#PLAY
- name: deploy
  hosts: all
  gather_facts: false
  become: true
  #TASKS  
  tasks:
    #RUN APT UPDATE
    - name: apt update
      #ACTION
      apt:  update_cache=yes
            force_apt_get=yes
            cache_valid_time=3600
    #RUN APT UPGRADE
    - name: apt upgrade
      #ACTION
      apt:  upgrade=dist
            force_apt_get=yes
            #RUN APT INSTALL NGINX
    - name: install nginx
      #ACTION
      apt:
        name:   ['nginx']
        state:  latest
    #CREATE FOLDER avaliacao1.com ON /var/www/ INSIDE THE BOX
    - name: create www directory
      #ACTION
      copy:
        src:  ../avaliacao2.com
        dest: /var/www/
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"#DEFINE PATH TO THE ANSIBLE PLAYBOOK
    #DELETE THE DEFAULT NGINX SITE CONFIGURATION
    - name: delete default nginx site
      #ACTION
      file:
        path: /etc/nginx/sites-available/default
        state: absent
      notify: restart nginx
    #CREATE THE SITE CONFIGURATION (nginx.conf.j2) TO SERVE WHATS INSIDE /var/www/avaliacao1.com
    - name: copy nginx site.conf
      #ACTION
      ansible.builtin.copy:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx
    #RUN APT INSTALL SAMBA
    - name: install samba
      #ACTION
      apt:
        name: ['samba']
        state: latest
    #CREATE SHARED DIRECTORY
    - name: create shared directory
      #ACTION
      file:
        path: /home/vagrant/samba/
        state: directory
        mode: '0775'
        owner: "vagrant"
        group: "vagrant"
    #PUT  arquivoImportante.txt INSIDE THE SHARED DIRECTORY
    - name: send arquivoImportante.txt
      copy:
        src: ./arquivoImportante.txt
        dest: /home/vagrant/samba/
        mode: '0766'
        owner: "vagrant"
        group: "vagrant"
    #ADD SHARED DIRECTORY TO THE SAMBA CONFIG
    - name: add shared directory config
      #ACTION
      blockinfile:
        path:  /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [samba]
            comment = Samba on Ubuntu
            path = /home/vagrant/samba
            read only = yes
            browsable = yes
      notify: Reload Samba
    #DEFINE SAMBA USER
    - name: set Samba passwords for each user
      #ACTION
      shell: "printf '123\n123\n' | smbpasswd -a vagrant"
  handlers:
    #RESTART SAMBA SERVICE
    - name: Reload Samba
      service:
        name: smbd
        state: restarted
    - name: restart nginx
      service:
        name: nginx
        state: restarted